openapi: 3.0.3
info:
  title: DacQ API
  description: DacQ Score Server API
  contact:
    name: DacQ Project Repository
    url: https://github.com/dacq-trap/dacq
  version: 1.0.0
servers:
  - url: http://localhost:7070/api
    description: Local Dev Environment
paths:
  /ping:
    $ref: ./ping/index.yaml
  /oauth/callback:
    $ref: ./oauth/callback.yaml
  /oauth/code:
    $ref: ./oauth/code.yaml
  /users/me:
    $ref: ./users/me.yaml
tags:
  - name: General
    description: General API
  - name: OAuth
    description: OAuth API
  - name: Users
    description: Users API
