openapi: 3.0.3
info:
  title: DacQ API
  description: DacQ Score Server API
  contact:
    name: DacQ Project Repository
    url: https://github.com/dacq-trap/dacq
  version: 1.0.0
servers:
  - url: http://localhost:7070/api
    description: Local Dev Environment

paths:
  /ping:
    $ref: ./paths/ping/index.yaml
  /oauth/callback:
    $ref: ./paths/oauth/callback.yaml
  /oauth/code:
    $ref: ./paths/oauth/code.yaml
  /users/me:
    $ref: ./paths/users/me.yaml
  /competitions:
    $ref: ./paths/competitions/index.yaml
  /competitions/{competitionId}:
    $ref: ./paths/competitions/competitionId.yaml
  /competitions/{competitionId}/data:
    $ref: ./paths/competitions/competitionId.data.yaml
  /competitions/{competitionId}/answer:
    $ref: ./paths/competitions/competitionId.answer.yaml
  /competitions/{competitionId}/leaderboard:
    $ref: ./paths/competitions/competitionId.leaderboard.yaml
  /competitions/{competitionId}/teams:
    $ref: ./paths/competitions/competitionId.teams.yaml
  /competitions/{competitionId}/submissions:
    $ref: ./paths/competitions/competitionId.submissions.yaml
  /submissions/{submissionId}:
    $ref: ./paths/submissions/submissionId.yaml
  /teams/{teamId}:
    $ref: ./paths/teams/teamId.yaml
  /teams/me:
    $ref: ./paths/teams/me.yaml
  /teams/me/{competitionId}:
    $ref: ./paths/teams/me.competitionId.yaml
  /teams/merge:
    $ref: ./paths/teams/merge.yaml
  /teams/merge/vote:
    $ref: ./paths/teams/merge.vote.yaml
  /teams/{teamId}/merge:
    $ref: ./paths/teams/teamId.merge.yaml

tags:
  - name: General
    description: General API
  - name: OAuth
    description: OAuth API
  - name: Users
    description: Users API
  - name: Competitions
    description: Competitions API
  - name: Authors
    description: Competition Authors API
  - name: Teams
    description: Teams API
  - name: Submissions
    description: Submissions API

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: dq_session
