openapi: 3.0.3
info:
  title: DacQ API
  description: DacQ Score Server API
  contact:
    name: DacQ Project Repository
    url: https://github.com/dacq-trap/dacq
  version: 1.0.0
servers:
  - url: http://localhost:7070/api
    description: Local Dev Environment
paths:
  /ping:
    $ref: ./ping/index.yaml
  /oauth/callback:
    $ref: ./oauth/callback.yaml
  /oauth/code:
    $ref: ./oauth/code.yaml
  /users/me:
    $ref: ./users/me.yaml
  /competitions:
    get:
  /competitions/{cid}:
    get:
    post:
      description: 参加登録
  /competitions/{cid}/leaderbord:
    get:
  /competitions/{cid}/teams:
    get:
  /competitions/{cid}/submissions:
    post:
    get:
      description: 自チームの提出一覧
  /competitions/{cid}/data:
    get:
  /submissions/{sid}:
    get:
    patch:
      description: コメントの変更
  /teams/{tid}:
    get:
    put:
  /teams/me:
    get:
  /teams/me/{cid}:
    get:
  /teams/me/merge:
    post:
    get:
tags:
  - name: General
    description: General API
  - name: OAuth
    description: OAuth API
  - name: Users
    description: Users API