name: client

on:
  push:
    branches:
      - main
    paths:
      - client/**/*
      - .github/workflows/client.yml
  pull_request:
    paths:
      - client/**/*
      - .github/workflows/client.yml

jobs:
  packages:
    name: Check npm install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Run npm ci
        run: npm ci
  build:
    name: Run build
    runs-on: ubuntu-latest
    needs: [packages]
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Run npm ci
        run: npm ci
      - name: Run build
        run: npm run build
  format:
    name: Run format
    runs-on: ubuntu-latest
    needs: [packages]
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Run npm ci
        run: npm ci
      - name: Run build
        run: npm run fmt:check
  lint:
    name: Run lint with reviewdog
    runs-on: ubuntu-latest
    needs: [packages]
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'