name: openapi

on:
  push:
    branches:
      - main
    paths:
      - schema/openapi/**
      - .github/workflows/openapi.yaml
  pull_request:
    paths:
      - schema/openapi/**
      - .github/workflows/openapi.yaml

jobs:
  openapi-lint:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schema/openapi
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install spectral
        run: npm install --location=global @stoplight/spectral-cli
      - name: Run spectral
        run: spectral lint openapi.yaml --ruleset .spectral.yaml 
  generate-check:
    name: Check if it's OK to generate client code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: client/package-lock.json
      - name: Run npm ci
        run: npm ci
      - name: Regenerate with OpenAPI
        run: npm run gen-api
