name: openapi

on:
  push:
    branches:
      - main
    paths:
      - schema/openapi/**
      - .github/workflows/openapi.yaml
  pull_request:
    paths:
      - schema/openapi/**
      - .github/workflows/openapi.yaml

jobs:
  openapi-lint:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schema/openapi
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Spectral
        uses: stoplightio/spectral-action@v0.8.8
        with:
          file_glob: openapi.yaml
          spectral_ruleset: .spectral.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          event_name: ${{ github.event_name }}
  generate-check:
    name: Check if it's OK to generate client code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: client/package-lock.json
      - name: Run npm ci
        run: npm ci
      - name: Regenerate with OpenAPI
        run: npm run gen-api
