name: server

on:
  push:
    branches:
      - main
    paths:
      - server/**/*
      - .github/workflows/server.yml
  pull_request:
    paths:
      - server/**/*
      - .github/workflows/server.yml

env:
  GO_VERSION: 1.18

jobs:
  mod:
    name: Module Download
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Mod Cache
        id: mod-cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: mod-${{ hashFiles('**/go.sum') }}
      - name: Setup Go
        if: steps.mod-cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Module Download
        if: steps.mod-cache.outputs.cache-hit != 'true'
        run: go mod download
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          working-directory: server
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    needs: [mod]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set Mod Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: mod-${{ hashFiles('**/go.sum') }}
      - name: Build
        run: go build
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    needs: [mod]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set Mod Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: mod-${{ hashFiles('**/go.sum') }}
      - name: Run Test
        run: go test ./... -v
